var gulp     = require('gulp');
var config   = require('../../config').iconFont;
var template = require('gulp-swig');
var rename   = require('gulp-rename');

module.exports = function(codepoints, options) {

  var iconSass = template({
    data: {
      icons: codepoints.map(function(icon) {
        return {
          name: icon.name,
          code: icon.codepoint.toString(16)
        }
      }),
      fontName: config.options.fontName,
      fontPath: config.fontPath,
      className: config.className,
      comment: 'DO NOT EDIT DIRECTLY!\n  Generated by gulp/tasks/iconFont.js\n  from ' + config.template
    }
  });

  gulp.src(config.template)
    .pipe(iconSass)
    .pipe(rename(config.sassOutputName))
    .pipe(gulp.dest(config.sassDest));
};
